-- This file is generated by tools/generate-fonts.ps1 — do not edit by hand
local ADDON_NAME = ...

local function RegisterArtisanFonts()
    local LSM = LibStub and LibStub("LibSharedMedia-3.0", true)
    if not LSM then return end

    local basePath = "Interface/AddOns/" .. ADDON_NAME .. "/media/"

    local fonts = {        { key = 'CreatoDisplay-Black', file = 'CreatoDisplay-Black.ttf' },
        { key = 'CreatoDisplay-Bold', file = 'CreatoDisplay-Bold.ttf' },
        { key = 'CreatoDisplay-ExtraBold', file = 'CreatoDisplay-ExtraBold.ttf' },
        { key = 'CreatoDisplay-Light', file = 'CreatoDisplay-Light.ttf' },
        { key = 'CreatoDisplay-Medium', file = 'CreatoDisplay-Medium.ttf' },
        { key = 'CreatoDisplay-Regular', file = 'CreatoDisplay-Regular.ttf' },
        { key = 'CreatoDisplay-Thin', file = 'CreatoDisplay-Thin.ttf' },
        { key = 'Exo-Black', file = 'Exo-Black.ttf' },
        { key = 'Exo-Bold', file = 'Exo-Bold.ttf' },
        { key = 'Exo-ExtraBold', file = 'Exo-ExtraBold.ttf' },
        { key = 'Exo-Light', file = 'Exo-Light.ttf' },
        { key = 'Exo-Medium', file = 'Exo-Medium.ttf' },
        { key = 'Exo-Regular', file = 'Exo-Regular.ttf' },
        { key = 'Exo-SemiBold', file = 'Exo-SemiBold.ttf' },
        { key = 'SourceSansPro-Black', file = 'SourceSansPro-Black.ttf' },
        { key = 'SourceSansPro-Bold', file = 'SourceSansPro-Bold.ttf' },
        { key = 'SourceSansPro-ExtraLight', file = 'SourceSansPro-ExtraLight.ttf' },
        { key = 'SourceSansPro-Light', file = 'SourceSansPro-Light.ttf' },
        { key = 'SourceSansPro-Regular', file = 'SourceSansPro-Regular.ttf' },
        { key = 'SourceSansPro-Semibold', file = 'SourceSansPro-Semibold.ttf' },
    }

    for _, f in ipairs(fonts) do
        local path = basePath .. f.file
        LSM:Register("font", f.key, path)
    end
end

-- Expose the register function so artisan.lua can call it
Artisan_RegisterFonts = RegisterArtisanFonts
